services:
  - type: web
    name: whatsapp-aesthetic-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bot.py
    envVars:
      - key: PORT
        value: 10000
